version: '3.8'

services:
  url-shortener:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      STORAGE_TYPE: postgres
      POSTGRES_DSN: "postgres://user:password@postgres:5432/shortener?sslmode=disable"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
